services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  redis:
    image: valkey/valkey:8.1-alpine
